name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: bun run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: bun test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: bun run build
      - name: Test built executable
        env:
          TODOIST_API_TOKEN: test
        run: |
          timeout 5s bun dist/index.js || test $? = 124
          echo "✓ Server starts successfully"

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Build Docker image
        run: docker build -t todoist-mcp-server .
      - name: Test Docker container
        env:
          TODOIST_API_TOKEN: test
        run: |
          timeout 5s docker run --rm -e TODOIST_API_TOKEN="$TODOIST_API_TOKEN" todoist-mcp-server || test $? = 124
          echo "✓ Docker container starts successfully"
